### ISSUE TITLE
reload doesn't works

### ISSUE THREAD

**Issue by cupen** [opsdroid/opsdroid#1047]
opsdroid v0.15.4
python3.7.3

`./configuration.yml`
```
## Set the logging level
logging:
  level: info
  path: /dev/null
  console: true

## Set the location for opsdroid to install modules
# module-path: "."

## Show welcome message
welcome-message: true
timezone: 'Asia/Shanghai'

## Configure the web server
web:
  host: '127.0.0.1'
  port: 8081
#   ssl:
#     cert: /path/to/cert.pem
#     key: /path/to/key.pem

parsers:
  ## Regex (http://opsdroid.readthedocs.io/en/stable/matchers/regex)
  - name: regex
    enabled: true

  ## Crontab (http://opsdroid.readthedocs.io/en/stable/matchers/crontab)
  - name: crontab
    enabled: true

connectors:
  - name: websocket
    bot-name: "opsdroid"
    max-connections: 10
    connection-timeout: 10

databases:
  sqlite:
    file: "chatops.db"
    table: "chatops"


## Skill modules
skills:
  - name: devtools
```

```
$ opsdroid
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at: 
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
INFO opsdroid.database.sqlite: Connected to sqlite /home/cupen/.local/share/opsdroid/sqlite.db
INFO opsdroid.core: Opsdroid is now running, press ctrl+c to exit.
INFO opsdroid.web: Started web server on http://127.0.0.1:8081
INFO aiohttp.access: 127.0.0.1 [19/Jul/2019:05:38:38 +0000] "POST /connector/websocket HTTP/1.1" 200 252 "-" "-"
INFO opsdroid.core: Received stop signal, exiting.
INFO opsdroid.core: Removing skills...
INFO opsdroid.core: Removed devtools
INFO opsdroid.core: Removed devtools
INFO opsdroid.core: Removed devtools
INFO opsdroid.core: Removed apebot
INFO opsdroid.core: Stopping connector websocket...
INFO opsdroid.connector.websocket: websocket connection closed
INFO opsdroid.core: Stopped connector websocket
INFO opsdroid.core: Stopping database sqlite...
INFO opsdroid.core: Stopped database sqlite
INFO opsdroid.core: Stopping web server...
INFO aiohttp.access: 127.0.0.1 [19/Jul/2019:05:38:38 +0000] "GET /connector/websocket/7587eb7c-a9e7-11e9-bccd-e0d55e4be78e HTTP/1.1" 101 0 "-" "-"
INFO opsdroid.core: Stopped web server
INFO opsdroid.core: Stopping cron...
INFO opsdroid.core: Stopped cron
INFO opsdroid.core: Stopping pending tasks...
INFO opsdroid.core: Stopped pending tasks
INFO opsdroid.loader: Loaded config from configuration.yaml.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
WARNING opsdroid.core: Function based skills are deprecated and will be removed in a future release. Please use class-based skills instead.
ERROR opsdroid.core: Caught exception
Traceback (most recent call last):
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 347, in run_skill
    await skill(self, config, message)
  File "/home/cupen/.local/share/opsdroid/opsdroid-modules/skill/devtools/__init__.py", line 8, in reload
    await opsdroid.reload()
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 215, in reload
    self.load()
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 162, in load
    self.train_parsers(self.modules["skills"])
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 281, in train_parsers
    asyncio.gather(*tasks, loop=self.eventloop))
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 526, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/connector/websocket/__init__.py", line 122, in send_message
    message.target = next(iter(self.active_connections))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 120, in handle_async_exception
    context['future'].result()
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 353, in run_skill
    _("Whoops there has been an error")))
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/events.py", line 193, in respond
    return await super().respond(response)
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/events.py", line 100, in respond
    await opsdroid.send(event)
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 490, in send
    return await event.connector.send(event)
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/connector/__init__.py", line 196, in send
    return await self.events[type(event)](self, event)
RuntimeError: coroutine raised StopIteration
ERROR opsdroid.core: {'message': 'Task exception was never retrieved', 'exception': RuntimeError('coroutine raised StopIteration'), 'future': <Task finished coro=<OpsDroid.run_skill() done, defined at /home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py:339> exception=RuntimeError('coroutine raised StopIteration')>}
Traceback (most recent call last):
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/bin/opsdroid", line 10, in <module>
    sys.exit(main())
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/__main__.py", line 221, in main
    opsdroid.run()
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 145, in run
    self.eventloop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 582, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```

**Comment by jacobtomlinson** [comment]
Migrated this issue to the main repo as it will be a problem with the core.
