### ISSUE TITLE
Error when logging not specified in config

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#115]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/__main__.py", line 109, in <module>
    main()
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/__main__.py", line 102, in main
    configure_logging(opsdroid.config)
  File "/Users/jacob/Projects/opsdroid/opsdroid/opsdroid/__main__.py", line 23, in configure_logging
    logfile_path = config["logging"]["path"]
TypeError: string indices must be integers
```

**Comment by jacobtomlinson** [comment]
Turns out this was because I had a different config file with the old logging syntax.
