### ISSUE TITLE
Slack connector crashes after running dance several times

### ISSUE THREAD

**Issue by iguyking** [opsdroid/opsdroid#1217]
# Description
Slack connector crashes after running dance several times in a row

## Steps to Reproduce
Launch opsdroid with slack connector configured with bot token
go the channel connected in and run dance 3+ times in  a row

## Expected Functionality
Opsdroid keeps running fine

## Experienced Functionality
Opsdroid crashes with the following error:
```
ERROR slack.rtm.client: When calling '#process_message()' in the 'opsdroid.connector.slack' module the following error was raised: 'user'
Traceback (most recent call last):
  File "C:\Users\koe4945\desktop\git\personal\ops\venv\Scripts\opsdroid-script.py", line 11, in <module>
    load_entry_point('opsdroid', 'console_scripts', 'opsdroid')()
  File "c:\users\koe4945\desktop\git\personal\ops\venv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\koe4945\desktop\git\personal\ops\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\koe4945\desktop\git\personal\ops\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\koe4945\desktop\git\personal\ops\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\koe4945\desktop\git\personal\ops\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\koe4945\desktop\git\personal\ops\opsdroid\opsdroid\cli\start.py", line 31, in start
    opsdroid.run()
  File "c:\users\koe4945\desktop\git\personal\ops\opsdroid\opsdroid\core.py", line 161, in run
    self.eventloop.run_until_complete(asyncio.gather(*pending))
  File "C:\Users\koe4945\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\users\koe4945\desktop\git\personal\ops\python-slackclient\slack\rtm\client.py", line 339, in _connect_and_read
    await self._read_messages()
  File "c:\users\koe4945\desktop\git\personal\ops\python-slackclient\slack\rtm\client.py", line 390, in _read_messages
    await self._dispatch_event(event, data=payload)
  File "c:\users\koe4945\desktop\git\personal\ops\python-slackclient\slack\rtm\client.py", line 437, in _dispatch_event
    rtm_client=self, web_client=self._web_client, data=data
  File "c:\users\koe4945\desktop\git\personal\ops\opsdroid\opsdroid\connector\slack\__init__.py", line 104, in process_message
    user_info = await self.lookup_username(message["user"])
KeyError: 'user'
ERROR: Unhandled exception in opsdroid, exiting...
```

## Versions
- **Opsdroid version:**  v0.16.0+62.g620590f
- **Python version:**  3.7.3
- **OS/Docker version:**  Windows 10

## Configuration File
Please include your version of the configuration file below.

```yaml
connectors:
  - name: slack
    # required
    api-token: "[...bot token...]"

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
After some investigation it seems that when you use the dance skill the bot responds with an image link. Slack automatically replaces the link with the actual image and this triggers a `message_changed` event which our connector currently doesn't handle. This must be one difference between the official Slack library and the third party one we were using before.

I've raised #1220 to resolve this.
