### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed in Slack Connector

### ISSUE THREAD

**Issue by daniccan** [opsdroid/opsdroid#1232]
# Description
I am trying to build a Slack bot using Opsdroid (master branch). When running `opsdroid start`, I get an error where the Opsdroid bot fails to connect with the Slack Workspace.

## Steps to Reproduce
1. Install opsdroid
```
pip install git+https://github.com/opsdroid/opsdroid.git
```

2. Create `configuration.yaml` with following content
```
welcome-message: true

connectors:
  - name: slack
    api-token: "<Bot OAuth Token>"

skills:
  - name: hello
```

3. Start opsdroid

```
opsdroid start
```

## Expected Functionality
The expected functionality is for the Opsdroid Bot to get connected with Slack Workspace and interact with the Slack user as per the configured skill.

## Experienced Functionality
The Opsdroid Bot failed to connect with the Slack Workspace with the following error:

```
INFO opsdroid.connector.slack: Connecting to Slack
Traceback (most recent call last):
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.6/asyncio/base_events.py", line 820, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 846, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/opsdroid/connector/slack/__init__.py", line 55, in connect
    self.auth_info = (await self.slack.api_call("auth.test")).data
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/slack/web/base_client.py", line 229, in _send
    http_verb=http_verb, api_url=api_url, req_args=req_args
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/slack/web/base_client.py", line 259, in _request
    async with session.request(http_verb, api_url, **req_args) as res:
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/daniccan/c8/OpsDroid/c8-alertbot/env/lib/python3.6/site-packages/aiohttp/connector.py", line 941, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host www.slack.com:443 ssl:default [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)]
```

## Versions
- **Opsdroid version:** master branch in git
- **Python version:** 3.6.8
- **OS/Docker version:** Ubuntu 18.04 LTS

## Configuration File
Please include your version of the configuration file below.

```yaml
welcome-message: true

connectors:
  - name: slack
    api-token: "<Bot OAuth Token>"

skills:
  - name: hello
```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
It looks like the SSL certificate for Slack is being rejected. Do you have the certificate bundle installed ([instructions](https://www.techrepublic.com/article/how-to-install-ca-certificates-in-ubuntu-server/))?

**Comment by daniccan** [comment]
How do I get the certificate bundle of Slack?

**Comment by daniccan** [comment]
This looks like an issue with the `websocket-client` library version 0.48.0 and above. FYI, https://github.com/websocket-client/websocket-client/issues/451#issuecomment-417918570. I am unable to lock on to version 0.47.0 of the library due to another dependency. 

```
pkg_resources.DistributionNotFound: The 'websocket-client==0.48.0' distribution was not found and is required by ibm-watson
```

**Comment by jacobtomlinson** [comment]
> How do I get the certificate bundle of Slack?

You just need the main certificate bundle. Slack should be signed by one of the root certs.

> his looks like an issue with the websocket-client library version 0.48.0 and above.

That issue is discussing whether or not to use certifi for systems with a misconfigured certificate bundle.

My preference here would be for you to correctly configure your certificate bundle (as per the instructions I linked to). If your certificate bundle is in a non-standard location then you can point to it with the env var `WEBSOCKET_CLIENT_CA_BUNDLE`.

Could you try running `sudo apt-get install ca-certificates -y` and see if that resolves your issue?

**Comment by daniccan** [comment]
I tried both the above with no success.

**Comment by jacobtomlinson** [comment]
Are you able to locate your ca cert bundle on your system and point `WEBSOCKET_CLIENT_CA_BUNDLE` to it? They are usually in `/etc/ssl/certs` or `/usr/share/ca-certificates`.

**Comment by jacobtomlinson** [comment]
Also random question but is the time correct on your system? Sometimes certs can fail when the clock is wrong.

**Comment by daniccan** [comment]
The time is correct on my system. It is in IST. Hope that is not a problem. Also, I see a bunch of certificates in `/etc/ssl/certs`. What would be the name of the cert bundle required for slack?

**Comment by jacobtomlinson** [comment]
IST will be fine. You don't really need to know which cert authority they use, just ensure you have an up to date set.

Looking at their website though they seem to use Digicert.

![image](https://user-images.githubusercontent.com/1610850/68039945-23269a00-fcc5-11e9-893c-629e46c51ddb.png)

Could you try `export WEBSOCKET_CLIENT_CA_BUNDLE=/etc/ssl/certs`.

**Comment by daniccan** [comment]
Using the `certifi` library and fetching the certificate fixed the issue. Updated the PR with the changes.
