### ISSUE TITLE
Error Creating a custom connector to Microsoft Bot Framework 

### ISSUE THREAD

**Issue by igorfcardoso** [opsdroid/opsdroid#1417]
Hi, I'm trying to add a custom connector to Microsoft Bot Framework following the "Creating a custom connector" from Opsdroid Docs guide. I'm trying to use the default code, overwriting just a few lines to test the behaviour from the code as follow:

On configuration.yaml: 
```
botframework:
    path: ./botframework.py
``` 

On botframework.py:
```
import time

# We recommend you use the official library
# for your chat service and import it here
#import chatlibrary

# Import opsdroid dependencies
from opsdroid.connector import Connector, register_event
from opsdroid.events import Message

class BotFramework(Connector):

  def __init__(self, config):
    # Init the config for the connector
    self.name = "MyConnector" # The name of your connector
    self.config = config # The config dictionary to be accessed later
    self.default_target = "MyDefaultRoom" # The default room for messages to go

  async def connect(self, opsdroid):
    # Create connection object with chat library
    #self.connection = await chatlibrary.connect()
    self.connection = 0

  async def listen(self, opsdroid):
    # Listen for new messages from the chat service
    while True:
      # Get raw message from chat
      raw_message = await self.connection.get_next_message()

      # Convert to opsdroid Message object
      #
      # Message objects take a pointer to the connector to
      # allow the skills to call the respond method
      message = Message(raw_message.text, raw_message.user,
                        raw_message.room, self)

      # Parse the message with opsdroid
      await opsdroid.parse(message)

  @register_event(Message)
  async def send_message(self, message):
    # Send message.text back to the chat service
    await self.connection.send(message.text, message.user,
                               message.target)

  async def disconnect(self, opsdroid):
    # Disconnect from the chat service
    await self.connection.disconnect()
```

No matter what changes I make on the botframework.py, the error is the same:

```  
INFO opsdroid.logging: ========================================
INFO opsdroid.logging: Started opsdroid v0.17.1.
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml.
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration. This will cause skills which store things in memory to lose data when opsdroid is restarted.
Traceback (most recent call last):
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Igor Cardoso\AppData\Local\Programs\Python\Python37\Scripts\opsdroid.exe\__main__.py", line 7, in <module>
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\opsdroid\cli\start.py", line 42, in start
    opsdroid.run()
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\opsdroid\core.py", line 158, in run
    self.sync_load()
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\opsdroid\core.py", line 177, in sync_load
    self.eventloop.run_until_complete(self.load())
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\opsdroid\core.py", line 186, in load
    await self.start_connectors(self.modules["connectors"])
  File "c:\users\igor cardoso\appdata\local\programs\python\python37\lib\site-packages\opsdroid\core.py", line 315, in start_connectors
    connector = cls(connector_module["config"], self)
TypeError: __init__() takes 2 positional arguments but 3 were given
```
I'm using Python 3.7.0, opsdroid v0.17.1
I have tried to run another connector and it runs without a problem.

**Comment by jacobtomlinson** [comment]
Hmm looks like this docs may be out of date. The `__init__` method should look like this `def __init__(self, config, opsdroid)`.

See the base class for reference. 

https://github.com/opsdroid/opsdroid/blob/76ccc9f7ce3c40a08e198247421a4a97a3f61332/opsdroid/connector/__init__.py#L40

**Comment by igorfcardoso** [comment]
Thanks Jacob. 
```
def __init__(self, config, opsdroid=None):
```
Solved part of the problem. 
The other problem I found is that:
```
async def listen(self, opsdroid):
```
Can't have opsdroid object on it. So like this:
```
async def listen(self):
```
And all worked! Thanks!
