### ISSUE TITLE
Error when receiving bot message

### ISSUE THREAD

**Issue by olig89** [opsdroid/opsdroid#1498]
# Description
I have a skill that, at its core, reacts to a webhook from a service which reports when the user interacts with it. If certain criteria are met - the bot looks up the user’s slackID in a mongoDB and sends that user a direct message.

I use aspects of this code in other skills and they work without issue but when combined with sending the user a message, the bot will frequently fall over with one of the reported errors below.

## Expected Functionality
Based on the json received from the webhook, if certain criteria are met, the relevant user is sent a message. If an extra set of details are included in the user's mongoDB entry, a message is also sent to a second user. Messages are sent using two instances of Message from opsdroid.message (like in the example skills)

Worth mentioning in the same skill I am also using an aiohttp POST to invite those users to a channel (using a different user-token) as a way of getting around constraints with the legacy bot permissions. That part of the function works fine in isolation but I mention in case there is unseen crossover.

## Experienced Functionality
The skill works fine some of the time but will often error-out with the following:
```
ERROR slack.rtm.client: When calling '#wrapper()' in the 'opsdroid.connector.slack.events' module the following error was raised: 'bot_id'

Traceback (most recent call last):
File "/usr/local/bin/opsdroid", line 8, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/opsdroid/cli/start.py", line 42, in start
opsdroid.run()
File "/usr/local/lib/python3.7/site-packages/opsdroid/core.py", line 165, in run
self.eventloop.run_until_complete(asyncio.gather(*pending))
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "/usr/local/lib/python3.7/site-packages/slack/rtm/client.py", line 339, in _connect_and_read
await self._read_messages()
File "/usr/local/lib/python3.7/site-packages/slack/rtm/client.py", line 390, in _read_messages
await self._dispatch_event(event, data=payload)
File "/usr/local/lib/python3.7/site-packages/slack/rtm/client.py", line 437, in _dispatch_event
rtm_client=self, web_client=self._web_client, data=data
File "/usr/local/lib/python3.7/site-packages/opsdroid/connector/slack/events.py", line 139, in wrapper
event = await f(self, event, channel)
File "/usr/local/lib/python3.7/site-packages/opsdroid/connector/slack/events.py", line 193, in create_room_message
return await self.message_subtypes[msgtype](event, channel)
File "/usr/local/lib/python3.7/site-packages/opsdroid/connector/slack/events.py", line 229, in handle_bot_message
if event["bot_id"] != self.connector.bot_id: # pragma: nocover
KeyError: 'bot_id'
ERROR: Unhandled exception in opsdroid, exiting...
```
Also the log is littered with the following warning appearing after a random webhook trigger, usually the iteration before the error occurs
```WARNING slack.rtm.client: Websocket was closed.```

and recently, without any webhook interaction prompting it, I have seen these cropping up:
```ERROR opsdroid.connector.slack.events: Username lookup failed for 'user'.```

## Versions
- **OS/Docker version:** Running latest dockerimage available on Unraid

## Configuration File
Please include your version of the configuration file below.

```yaml
## Slack (core)
  slack:
    # required
    token: "xoxb-XXXXXX"
    # optional
    bot-name: "XXXXXX" # default "opsdroid"
    default-room: "XXXXXX" # default "#general"
    icon-emoji: ":robot_face:" # default ":robot_face:"
    connect-timeout: 10 # default 10 seconds
    chat-as-user: true # default false
```

## Additional Details

Happy to throw my code up somewhere if its easier to dig into, is a pet project so not sensitive in any way.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @olig89.

When a bot sends a message in Slack opsdroid will check to see if that bit is itself, or another bot. If it is another bot it will respond as if it was a user, if it is itself it will just ignore the message.

It looks like you may have another bot in your chat and there is a bug in the [check for other bot users](https://github.com/opsdroid/opsdroid/blob/7c38ffca869b35c31dff9273735e20c9c498cfb1/opsdroid/connector/slack/events.py#L225).

The solution to this would be to figure out what attribute we are looking for if it isn't `bot_id` and update the check.

Is this something you feel like you could fix in a PR?

**Comment by jacobtomlinson** [comment]
Did you find a solution to this @olig89 ?
