### ISSUE TITLE
Slack connector returns bare inputs of "https://someurl.tld" as "<https://someurl.tld>".  Possible to disable?

### ISSUE THREAD

**Issue by law** [opsdroid/opsdroid#1569]
# Description
I'm writing a simple skill to take a URL via message and run aiohttp against it.  Slack will 'helpfully' parse any URLs and pass them along to the Slack connector enclosed in <>'s (example: plain text input of "https://someurl.tld" becomes "<https://someurl.tld>").  Is there a way to disable this behavior?

## Steps to Reproduce
Write a skill that uses match_regex like so: 
```
  @match_regex("curl (.*)")
  async def http_client(self, opsdroid, config, message):
    target = message.regex.group(1)
    #pdb.set_trace()
    async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(ssl=False)) as session:
      async with session.get(target + '/') as resp:
        await message.respond(f"result: {resp.text()}")
        await message.respond(f"result status: {resp.status}")
        return await resp.text()
```

When testing with input of "curl http://google.com", Opsdroid/aiohttp will error out with
`aiohttp.client_exceptions.InvalidURL: %3Chttp://google.com%3E/`

(%3C and %3E are < and >, respectively)

If you uncomment the 'pdb.set_trace()' line and re-run with varying inputs, you'll notice the following correlations in the debugger: 

input: `curl http://google.com`
```
(Pdb) pp message.regex.group(0)
'curl <http://google.com>'
```

input: `curl notaurl`
```
(Pdb) pp message.regex.group(0)
'curl notaurl'
```

## Expected Functionality
Ideally, there would be no 'helpful' addition of < or > to a string matching a URL object: 

input: `curl http://google.com`
```
(Pdb) pp message.regex.group(0)
'curl http://google.com'
```

## Experienced Functionality
```
ERROR opsdroid.core: Exception when running skill 'myskill'.
Traceback (most recent call last):
  File "/Users/lwhalen/sandbox/infrabot/venv/lib/python3.7/site-packages/opsdroid/core.py", line 422, in run_skill
    return await skill(self, config, event)
  File "/Users/lwhalen/Library/Application Support/opsdroid/opsdroid-modules/skill/myskill/__init__.py", line 68, in http_client
    async with session.get(str(target) + '/') as resp:
  File "/Users/lwhalen/sandbox/infrabot/venv/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Users/lwhalen/sandbox/infrabot/venv/lib/python3.7/site-packages/aiohttp/client.py", line 473, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/Users/lwhalen/sandbox/infrabot/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 285, in __init__
    self.update_host(url)
  File "/Users/lwhalen/sandbox/infrabot/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 339, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: %3Chttp://google.com%3E/
INFO opsdroid.core: Received stop signal, exiting.
INFO opsdroid.core: Removing skills...
INFO opsdroid.core: Removed devtools.
INFO opsdroid.core: Removed devtools.
INFO opsdroid.core: Stopping connector websocket...
INFO opsdroid.core: Stopped connector websocket.
INFO opsdroid.core: Stopping database inmem...
INFO opsdroid.core: Stopped database inmem.
INFO opsdroid.core: Stopping web server...
INFO opsdroid.core: Stopped web server.
INFO opsdroid.core: Stopping cron...
INFO opsdroid.core: Stopped cron
INFO opsdroid.core: Stopping pending tasks...
INFO opsdroid.core: Stopped pending tasks.
INFO opsdroid.core: Bye!
INFO opsdroid.core: Exiting application with return code 0.
ERROR: Unhandled exception in opsdroid, exiting...
ERROR: Unhandled exception in opsdroid, exiting...
```

## Versions
- **Opsdroid version:** 0.19.0 (also reproduced in 0.17.0, 0.17.1, and 0.18.0)
- **Python version:** 3.7.7
- **OS/Docker version:** OS X Catalina

## Configuration File
Please include your version of the configuration file below.

```yaml
n/a
```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by FabioRosado** [comment]
Hello @law thank you for raising this issue, I can understand how annoying this might be. We are using the official slack library  on our connector and I'm assuming that either the library or slack itself is adding the `<>` to the url.  Perhaps we should update the the slack connector to avoid using that or on your skill you could write a regex to get only the url? 

Trying to match this regex `<(https?:\/\/.*)>` should cover your needs you can then grab that group and do something with it 🤔  Hopefully this helps

**Comment by law** [comment]
Most excellent, thank you.  Yes, I was going to do a naive search/replace on the string just to get the brackets out of there, but having the connector just return the bare input instead of trying to decorate it would be the ideal solution.

**Comment by jacobtomlinson** [comment]
I think the decoration is being added by Slack. I'm hesitant to do any cleaning in the connector. I feel like we should represent the Slack message as is.

I would suggest going with @FabioRosado's workaround.

**Comment by law** [comment]
I can understand that POV.  It does get more complicated the more 'decoration' is being added by Slack.  For example, they will gleefully (and silently) follow any 301-redirects a website gives, and rewrite the URL while still maintaining the original text.  In practice, it looks like this: 

input text: 
`blah blah http://somewebsitewitharedirect.com`

output as proffered by the connector: 
`blah blah <http://somewebsitewitharedirect.com|https://www.somewebsitewitharedirect.com>` (note the addition of 'www' and going from http to https) 

the upshot being that it's now a more complicated string to detect modification on, and then correct.  Not insurmountable, just... obnoxious.  Perhaps a generalized wrapper or attribute for "strip markdown formatting" would be appropriate, but my use-case might also be way out on the edge.  

Would a note in the documentation to "expect this behavior when parsing inputs from the Slack connector", perhaps with examples, be appropriate?  If so, would it be better in the Parser docs, the Connector docs, or someplace else?

**Comment by jacobtomlinson** [comment]
> Would a note in the documentation to "expect this behavior when parsing inputs from the Slack connector", perhaps with examples, be appropriate?

Yes I think adding this to the Slack connector docs would be the most appropriate course of action here. 

I would also be happy for a utility function to be added to the connector module. Something that users can import into their skill and use to strip formatting like this.
