### ISSUE TITLE
matcher in __init__ instead of as a decorator causes opsdroid to crash

### ISSUE THREAD

**Issue by law** [opsdroid/opsdroid#1596]
# Description
While trying to use a variable inside a `match_regex` matcher, calling the matcher in the `init` instead of as a decorator causes opsdroid to crash

## Steps to Reproduce
The following code in a skill causes Opsdroid to crash: 
```
class MySkill(Skill):

    def __init__(self, opsdroid, config):
        super().__init__(opsdroid, config)
        bot_name = self.opsdroid.get_connector('slack').bot_name # evaluates to 'mybot' in this example
        self.get_something = match_regex(r"{bot_name} do something")(self.get_something)

    async def get_something(self, opsdroid, config, message):
        # rest of method goes here
```

Full stack is:
```
$ opsdroid start
Opsdroid has a new configuration format since version 0.17.0, we will change your configuration now. Please read on how to migrate in the documentation.
Opsdroid has a new configuration format since version 0.17.0, we will change your configuration now. Please read on how to migrate in the documentation.
INFO opsdroid.logging: ========================================
INFO opsdroid.logging: Started opsdroid v0.19.0.
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml.
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at: 
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration. This will cause skills which store things in memory to lose data when opsdroid is restarted.
INFO opsdroid.connector.slack: Connecting to Slack.
INFO opsdroid.connector.slack: Connected successfully.
Traceback (most recent call last):
  File "/Users/lwhalen/sandbox/venv/bin/opsdroid", line 8, in <module>
    sys.exit(cli())
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/opsdroid/cli/start.py", line 43, in start
    opsdroid.run()
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/opsdroid/core.py", line 162, in run
    self.sync_load()
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/opsdroid/core.py", line 181, in sync_load
    self.eventloop.run_until_complete(self.load())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/opsdroid/core.py", line 190, in load
    self.setup_skills(self.modules["skills"])
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/opsdroid/core.py", line 258, in setup_skills
    skill_obj = func(self, skill["config"])
  File "/Users/lwhalen/Library/Application Support/opsdroid/opsdroid-modules/skill/myskill/__init__.py", line 27, in __init__
    self.get_environments = match_regex(f"mybot do something")(self.get_something)
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/opsdroid/matchers.py", line 55, in matcher
    func = add_skill_attributes(func)
  File "/Users/lwhalen/sandbox/venv/lib/python3.8/site-packages/opsdroid/helper.py", line 177, in add_skill_attributes
    func.skill = True
AttributeError: 'method' object has no attribute 'skill'
ERROR: Unhandled exception in opsdroid, exiting...
ERROR: Unhandled exception in opsdroid, exiting...
```

## Expected Functionality
Explain what should happen.
Method "get_something" should run without issue

## Experienced Functionality
Explain what happened instead(Please include the debug log).
Opsdroid crashes, with above stack

## Versions
- **Opsdroid version:**  0.19.0
- **Python version:**  3.8.4
- **OS/Docker version:** 19.03.8

## Configuration File
Please include your version of the configuration file below.
```
welcome-message: true
connectors:
  - name: websocket
  - name: slack
    token: $SLACK_TOKEN
skills:
  - name: myskill
    path: ./skills-cache/myskill
    no-cache: true
```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
I would expect this to work.

I assume there is some problem when decorating a bound method. It would be great to get this fixes as I think this opens up a lot of functionality around configuring skills from the YAML.
