### ISSUE TITLE
Error during installation on debian

### ISSUE THREAD

**Issue by thasos** [opsdroid/opsdroid#1677]
# Description
There is an error when we start opsdroid on debian (fresh install or in a docker container).

## Steps to Reproduce
```
$ docker run --rm -ti debian:sid
# apt update
# apt install python3 python3-pip git
# pip3 install opsdroid
# opsdroid start
```

## Expected Functionality
opsdroid start (it works with ubuntu)

## Experienced Functionality
Error while installing the packages for opsdroid v0.19.0 (I tested 0.18.0 too, same error)

## Versions
- **Opsdroid version: 0.19.0**
- **Python version: 3.9.0+**
- **OS/Docker version: debian:sid**

## Configuration File
default config file (untouched)

## Additional Details
error on start :
```
opsdroid@619d3f4459c2:~$ opsdroid start
INFO opsdroid.logging: ========================================
INFO opsdroid.logging: Started opsdroid v0.19.0.
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml.
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration. This will cause skills which store things in memory to lose data when opsdroid is restarted.
INFO opsdroid.loader: Cloning dance from remote repository.
INFO opsdroid.loader: Cloning hello from remote repository.
INFO opsdroid.web: Started web server on http://0.0.0.0:8080
INFO opsdroid.core: Opsdroid is now running, press ctrl+c to exit.
Traceback (most recent call last):
  File "/usr/local/bin/opsdroid", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/opsdroid/cli/start.py", line 43, in start
    opsdroid.run()
  File "/usr/local/lib/python3.9/dist-packages/opsdroid/core.py", line 167, in run
    pending = asyncio.Task.all_tasks()
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
ERROR: Unhandled exception in opsdroid, exiting...
ERROR: Unhandled exception in opsdroid, exiting...
ERROR: Unhandled exception in opsdroid, exiting...
sys:1: RuntimeWarning: coroutine 'ConnectorShell._parse_message' was never awaited
ERROR: Unhandled exception in opsdroid, exiting...
ERROR: Unhandled exception in opsdroid, exiting...
sys:1: RuntimeWarning: coroutine 'BaseEventLoop._create_server_getaddrinfo' was never awaited
sys:1: RuntimeWarning: coroutine 'parse_always' was never awaited
sys:1: RuntimeWarning: coroutine 'parse_event_type' was never awaited
ERROR: Unhandled exception in opsdroid, exiting...
ERROR: Unhandled exception in opsdroid, exiting...
```

**Comment by Cadair** [comment]
Think this is probably more of a Python 3.9 issue than a debian one. Thanks for the report :+1:
