### ISSUE TITLE
Bug when installing module requirements with pip 8.1.1

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#172]
```
DEBUG opsdroid.loader: b'Installing collected packages: feedparser'
DEBUG opsdroid.loader: b'Exception:'
DEBUG opsdroid.loader: b'Traceback (most recent call last):'
DEBUG opsdroid.loader: b'  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main'
DEBUG opsdroid.loader: b'    status = self.run(options, args)'
DEBUG opsdroid.loader: b'  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run'
DEBUG opsdroid.loader: b'    prefix=options.prefix_path,'
DEBUG opsdroid.loader: b'  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install'
DEBUG opsdroid.loader: b'    **kwargs'
DEBUG opsdroid.loader: b'  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install'
DEBUG opsdroid.loader: b'    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)'
DEBUG opsdroid.loader: b'  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files'
DEBUG opsdroid.loader: b'    isolated=self.isolated,'
DEBUG opsdroid.loader: b'  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files'
DEBUG opsdroid.loader: b'    prefix=prefix,'
DEBUG opsdroid.loader: b'  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme'
DEBUG opsdroid.loader: b'    i.finalize_options()'
DEBUG opsdroid.loader: b'  File "/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options'
DEBUG opsdroid.loader: b'    orig.install.finalize_options(self)'
DEBUG opsdroid.loader: b'  File "/usr/lib/python3.5/distutils/command/install.py", line 273, in finalize_options'
DEBUG opsdroid.loader: b'    raise DistutilsOptionError("can\'t combine user with prefix, "'
DEBUG opsdroid.loader: b"distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base"
DEBUG opsdroid.loader: b'You are using pip version 8.1.1, however version 9.0.1 is available.'
DEBUG opsdroid.loader: b"You should consider upgrading via the 'pip install --upgrade pip' command."
```

**Comment by jacobtomlinson** [comment]
Easiest solution is to upgrade pip

`pip install --upgrade pip`
