### ISSUE TITLE
Mattermost connector is broken

### ISSUE THREAD

**Issue by davdr** [opsdroid/opsdroid#1773]
# Description
The Mattermost connector is broken. It can connect to a Mattermost instance, but when sending a message to OpsDroid (using the Hello skill) you get:

```
ERROR opsdroid.core: Exception when running skill 'hello'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/opsdroid/core.py", line 465, in run_skill
    return await skill(event)
  File "/root/.local/share/opsdroid/opsdroid-modules/skill/hello/__init__.py", line 13, in hello
    await message.respond(text)
  File "/usr/local/lib/python3.8/site-packages/opsdroid/events.py", line 278, in respond
    "thinking-delay" in self.connector.configuration
AttributeError: 'NoneType' object has no attribute 'configuration'
WARNING mattermostdriver.websocket: Failed to establish websocket connection: 'NoneType' object has no attribute 'configuration'
```

## Steps to Reproduce
Configure the Mattermost connector and the Hello skill, start Opsdroid and send a message to the bot in Mattermost.

## Expected Functionality
A reply form the Hello skill.

## Experienced Functionality
No reply, and the above error in the Opsdroid logs.

## Versions
- **Opsdroid version:** 0.22.0
- **Python version:** 3.8
- **OS/Docker version:** N/A

## Configuration File
Please include your version of the configuration file below.

```yaml
welcome-message: false

connectors:
  ## Mattermost (core)
  mattermost:
    # Required
    token: "<redacted>"
    url: "<redacted>"
    team-name: "<redacted>"
    # Optional
    scheme: "https" # default: https
    port: 443 # default: 8065
    ssl-verify: true # default: true
    connect-timeout: 30 # default: 30

skills:
  ## Hello (https://github.com/opsdroid/skill-hello)
  hello: {}
  ## Seen (https://github.com/opsdroid/skill-seen)
  seen: {}
```

## Additional Details
Looks like this the Mattermost connector was missed in #1116 -- I'll submit a PR shortly to correct this.

**Comment by davdr** [comment]
PR #1774 submitted to fix this.
