### ISSUE TITLE
Opsdroid does not install with python 3.12

### ISSUE THREAD

**Issue by mprasil** [opsdroid/opsdroid#2011]
# Description

Opsdroid does not install with python 3.12. Most likely versioneer needs to be updated?

## Steps to Reproduce
With docker one can reproduce that with:

```
docker run -ti --rm python:3.12-slim pip install opsdroid
```

## Expected Functionality

Installation succeeds.

## Experienced Functionality

Installation fails with:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<pip-setuptools-caller>", line 34, in <module>
  File "/tmp/pip-install-l4nph302/opsdroid_b00332d724184742a9f10d42894092a7/setup.py", line 62, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pip-install-l4nph302/opsdroid_b00332d724184742a9f10d42894092a7/versioneer.py", line 1527, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/tmp/pip-install-l4nph302/opsdroid_b00332d724184742a9f10d42894092a7/versioneer.py", line 1454, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pip-install-l4nph302/opsdroid_b00332d724184742a9f10d42894092a7/versioneer.py", line 348, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
[end of output]
```

## Versions
- **Opsdroid version:** 0.28.0
- **Python version:** 3.12

**Comment by jacobtomlinson** [comment]
This should be resolved with #2024
