### ISSUE TITLE
Better error handling for bad config path in docker container

### ISSUE THREAD

**Issue by gabeduke** [opsdroid/opsdroid#219]
When passing a bad config location to Docker container the error returned should be more descriptive:

> opsdroid> ERROR asyncio: Fatal read error on pipe transport
> protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fcb72febdd8>
> …
> transport: <_UnixReadPipeTransport fd=0 polling>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/asyncio/unix_events.py", line 381, in _read_ready
>     data = os.read(self._fileno, self.max_size)
> OSError: [Errno 9] Bad file descriptor

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

**Comment by jacobtomlinson** [comment]
I think this is actually an issue with the websocket connector.

opsdroid/connector-websocket#1

**Comment by jacobtomlinson** [comment]
Actually after disabling the websocket connector I'm still getting the message so it's not that.

**Comment by gtseres** [comment]
It seems that the place where the issue occurs is `web.run_app()` of the `web.py`, but I'm not sure what the root cause is.

**Comment by fititnt** [comment]
This issue still exist.


```bash
# fititnt at bravo in /alligo/code/fititnt/chatops-wg-ia-python-opsdroid on git:master x [4:09:57]
$ docker run --rm  -p 8080:8080 -v $PWD/iapythonopsdroid/configuration.yaml:/etc/opsdroid/configuration.yaml:ro opsdroid/opsdroid:latest
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at: 
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things inmemory to lose data when opsdroid is restarted.
INFO opsdroid.loader: Cloning hello from remote repository
INFO opsdroid.loader: Cloning seen from remote repository
INFO opsdroid.loader: Cloning dance from remote repository
INFO opsdroid.loader: Cloning loudnoises from remote repository
INFO opsdroid.loader: Cloning shell from remote repository
opsdroid> ERROR asyncio: Fatal read error on pipe transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fa4173f6828>
transport: <_UnixReadPipeTransport fd=0 polling>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/unix_events.py", line 381, in _read_ready
    data = os.read(self._fileno, self.max_size)
OSError: [Errno 9] Bad file descriptor
INFO opsdroid.web: ======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)
```

And I can cofirm that even line "- name: websocket" commented on

```bash
# fititnt at bravo in /alligo/code/fititnt/chatops-wg-ia-python-opsdroid on git:master x [4:12:12]
$ cat $PWD/iapythonopsdroid/configuration.yaml | egrep -v "(^#.*|^$)"
welcome-message: true
connectors:
  - name: shell
  # Uncomment the connector(s) that you wish opsdroid to work on
skills:
  ## Hello world (https://github.com/opsdroid/skill-hello)
  - name: hello
  ## Last seen (https://github.com/opsdroid/skill-seen)
  - name: seen
  ## Dance (https://github.com/opsdroid/skill-dance)
  - name: dance
  ## Loud noises (https://github.com/opsdroid/skill-loudnoises)
  - name: loudnoises
   # Configurations for other skills uncomment desired skill to activate it.
```

**Comment by jacobtomlinson** [comment]
I am able to reproduce.

This bug seems to be in the connector-shell, not the connector-websocket as I stated above. 

If you include `-ti` in your docker command the interactive shell works.

**Comment by jacobtomlinson** [comment]
Ah looks like you beat me to it in #417 @fititnt. I'll also raise an issue on the shell connector as this should be caught and a useful error message should be printed.

**Comment by jacobtomlinson** [comment]
Raised opsdroid/connector-shell#3.
