### ISSUE TITLE
Not Implemented Error on fresh install

### ISSUE THREAD

**Issue by walker-w** [opsdroid/opsdroid#352]
# Description
installed opsdroid on windows 10 powershell using the command:
pip3 install opsdroid

When attempting to run the command opsdroid I get the error:
```powershell
Traceback (most recent call last):
  File "C:\Users\Walker\AppData\Local\Programs\Python\Python36\Scripts\opsdroid-script.py", line 11, in <module>
    load_entry_point('opsdroid==0.10.0', 'console_scripts', 'opsdroid')()
  File "c:\users\walker\appdata\local\programs\python\python36\lib\site-packages\opsdroid\__main__.py", line 125, in main
    with OpsDroid() as opsdroid:
  File "c:\users\walker\appdata\local\programs\python\python36\lib\site-packages\opsdroid\core.py", line 42, in __init__
    self.eventloop.add_signal_handler(sig, self.call_stop)
  File "c:\users\walker\appdata\local\programs\python\python36\lib\asyncio\events.py", line 481, in add_signal_handler
    raise NotImplementedError
NotImplementedError

```

## Steps to Reproduce
Please also include relevant information and steps to reproduce the bug/issue.

## Expected Functionality
Explain what should happen.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version: 0.10.0**
- **Python version: 3.6.3**
- **OS/Docker version: Windows 10**

## Configuration File
Default config

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

Currently opsdroid does not support native windows installs and makes some assumptions around that. This error looks to be coming from one of those assumptions.

I'm going to close this issue and open a new one for adding windows support because I expect there are more issues than just this.
