### ISSUE TITLE
FileNotFound error: No such file or directory: pip

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#385]
# Description
Honestly this issue might be just my own fault. I probably installed python 3 wrong when I first got my Macbook pro. Anyway, when I try to run opsdroid with a skill that contains a `requirements.txt`  I get a `FileNotFoundError: [Errno 2] No such file or directory: 'pip'` exception.

If I change 'pip' in  `opsdroid.loader.pip_install_deps`  for 'pip3' everything works fine.

Should a try/except be used just in case someone has the same issue?

## Steps to Reproduce
As this is an issue with my python install I'm not sure how to reproduce it...

## Expected Functionality
Opsdroid to run normally.

## Experienced Functionality
Explain what happened instead(Please include the debug log).

```python
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at: 
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.
Traceback (most recent call last):
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/__main__.py", line 140, in <module>
    init()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/__main__.py", line 137, in init
    main()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/__main__.py", line 130, in main
    opsdroid.start_loop()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/core.py", line 134, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/loader.py", line 222, in load_modules_from_config
    skills = self._load_modules('skill', config['skills'])
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/loader.py", line 271, in _load_modules
    self._install_module(config)
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/loader.py", line 317, in _install_module
    "/requirements.txt")
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/loader.py", line 112, in pip_install_deps
    stderr=subprocess.PIPE)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pip'
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 511, in __del__
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/unix_events.py", line 65, in close
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/unix_events.py", line 146, in remove_signal_handler
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

## Versions
- **Opsdroid version:** latest
- **Python version:** 2.7, 3.5
- **OS/Docker version:**  macOS High Sierra(10.13.2)

## Configuration File
My ~/.bash_profile as the following alias:

```bash
alias pip='/usr/local/bin/pip3.6'
```

## Additional Details

@jacobtomlinson  let me know what you think of this, thank you 👍

**Comment by jacobtomlinson** [comment]
I have come across this before. You need to have the pip command available in your path for opsdroid to install modules correctly. 

Are you using virtual environments?

**Comment by FabioRosado** [comment]
My interpreter in pycharm was set to my global python path when I got the error.
I tried to run a virtual environment and change the interpreter in pycharm, the error persisted still

**Comment by jacobtomlinson** [comment]
I would suggest that this is expected functionality as the command `pip` cannot be found and is required by opsdroid. However we should probably catch the `FileNotFoundError` and log an actually useful error message.

I would be open to also trying `pip3` if `pip` cannot be found though.

**Comment by FabioRosado** [comment]
Okay I'll play around with this tomorrow and see if the issue gets resolved, it might be helpful for someone else as well haha
