### ISSUE TITLE
Databases fail to load under 0.12

### ISSUE THREAD

**Issue by Cadair** [opsdroid/opsdroid#609]
# Description

When I configure opsdroid to use a database (tested with the matrix or mongo database) I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/opsdroid/__main__.py", line 201, in <module>
    init()
  File "/usr/local/lib/python3.6/site-packages/opsdroid/__main__.py", line 198, in init
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/opsdroid/__main__.py", line 192, in main
    opsdroid.start_loop()
  File "/usr/local/lib/python3.6/site-packages/opsdroid/core.py", line 131, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "/usr/local/lib/python3.6/site-packages/opsdroid/loader.py", line 266, in load_modules_from_config
    databases = self._load_modules('database', config['databases'])
  File "/usr/local/lib/python3.6/site-packages/opsdroid/loader.py", line 311, in _load_modules
    config["is_builtin"] = self.is_builtin_module(config)
  File "/usr/local/lib/python3.6/site-packages/opsdroid/loader.py", line 94, in is_builtin_module
    module_name=config["name"]
  File "/usr/local/lib/python3.6/importlib/util.py", line 89, in find_spec
    return _find_spec(fullname, parent.__path__)
AttributeError: module 'opsdroid.database' has no attribute '__path__'
```

## Steps to Reproduce

start opsdroid with a database config section.

## Expected Functionality

The database should load

## Experienced Functionality

opsdroid crashes

## Versions
- **Opsdroid version:** 0.12.1
- **Python version:** 3.6 (conda)
- **OS/Docker version:** arch inux

**Comment by jacobtomlinson** [comment]
Thanks for raising this!

**Comment by Cadair** [comment]
I tried to work out why it was going wrong, but everything I did lead to new and even more incomprehensible errors lol

**Comment by jacobtomlinson** [comment]
I've had a guess at what I think the problem is. If you feel like testing that PR I would appreciate it.

**Comment by Cadair** [comment]
while we are at it, have you seen the "changed in 3.7" on this: https://docs.python.org/3/library/importlib.html#importlib.util.find_spec

**Comment by jacobtomlinson** [comment]
Ah that looks like it! We haven't started on 3.7 support yet. I would be keen to run tests against it for a start. 

Hopefully it is still the same fix though.
