### ISSUE TITLE
aiohttp missing from requirements

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#73]
```
$ opsdroid --gen-config > /tmp/opsconfig.yml
Traceback (most recent call last):
  File "/opt/boxen/homebrew/bin/opsdroid", line 7, in <module>
    from opsdroid.__main__ import main
  File "/opt/boxen/homebrew/lib/python3.5/site-packages/opsdroid/__main__.py", line 8, in <module>
    from opsdroid.core import OpsDroid
  File "/opt/boxen/homebrew/lib/python3.5/site-packages/opsdroid/core.py", line 13, in <module>
    from opsdroid.parsers.apiai import parse_apiai
  File "/opt/boxen/homebrew/lib/python3.5/site-packages/opsdroid/parsers/apiai.py", line 6, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'
```

**Comment by jacobtomlinson** [comment]
Fixed in #74
