### ISSUE TITLE
localized error msgs fail due to _ not being found

### ISSUE THREAD

**Issue by petri** [opsdroid/opsdroid#763]
# Description

Logging in core.py fails.

## Steps to Reproduce
For example install slack connector and give bad token.

## Expected Functionality
There should be logging of the issue with the connector not being able to connect.

## Experienced Functionality
When logging, the _ variable that should be injected into scope by eg. gettext.install is not found and thus logging causes an unhandled exception. See Error output at the end of this issue.

## Versions
- **Opsdroid version:** 0.13.0
- **Python version:** 3.6
- **OS/Docker version:** MacOS Mojave

## Error output
```
INFO opsdroid.connector.slack: Connecting to Slack
Traceback (most recent call last):
  File "/Users/petri/Code/koodaamo/python36/bin/opsdroid", line 11, in <module>
    load_entry_point('opsdroid', 'console_scripts', 'opsdroid')()
  File "/Users/petri/Code/koodaamo/python36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/petri/Code/koodaamo/python36/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/petri/Code/koodaamo/python36/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/petri/Code/koodaamo/python36/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/petri/Code/koodaamo/opsdroid/opsdroid/__main__.py", line 196, in main
    opsdroid.load()
  File "/Users/petri/Code/koodaamo/opsdroid/opsdroid/core.py", line 156, in load
    self.start_connectors(self.modules["connectors"])
  File "/Users/petri/Code/koodaamo/opsdroid/opsdroid/core.py", line 251, in start_connectors
    self.eventloop.run_until_complete(connector.connect(self))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/Users/petri/Code/koodaamo/opsdroid/opsdroid/connector/slack/__init__.py", line 50, in connect
    connection = await self.slacker.rtm.start()
  File "/Users/petri/Code/koodaamo/python36/lib/python3.6/site-packages/aioslacker/__init__.py", line 97, in __request
    raise Error(response.error)
slacker.Error: invalid_auth
ERROR asyncio: Unhandled error in exception handler
context: {'client_session': <aiohttp.client.ClientSession object at 0x102f3ecc0>, 'message': 'Unclosed client session'}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1308, in call_exception_handler
    self._exception_handler(self, context)
  File "/Users/petri/Code/koodaamo/opsdroid/opsdroid/core.py", line 116, in handle_async_exception
    _LOGGER.error(_("Caught exception"))
NameError: name '_' is not defined
```

**Comment by FabioRosado** [comment]
I have tested the slack connector with a fake token as you suggested. I can confirm that opsdroid just crashes. The `NameError` exception is related to the `gettext` dependency but this is not a true reason why opsdroid crashed - lately when `opsdroid.core.handle_async_exception` is called it will always show that `NameError` exception.

I tried to replace the `_()` within the `handle_async_exception` and opsdroid still crashed when using a bad token, but in my case the Traceback is extremely long. 

We should change the `slack.connect` method to handle the `slacker.Error: invalid_auth` exception in order to avoid having opsdroid crashing this bad. 

Finally, one of the reason why this is happening is probably because we are using slacker instead of the older dependency - I will try to get this sorted either today or this week.

Btw keep up the great work @petri 😄 👍

**Comment by petri** [comment]
The traceback for me was extremely long as well - basically what I copy pasted ^ just repeated, over and over and over.. I now pulled the master and cannot reproduce the issue any more. I guess we can close this.

**Comment by FabioRosado** [comment]
Can you confirm that we are still getting a traceback similar to this tho?
```python
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/__main__.py", line 206, in <module>
    init()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/__main__.py", line 203, in init
    main()
  File "/Users/fabiorosado/.local/share/virtualenvs/opsdroid-13bLHlYD/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fabiorosado/.local/share/virtualenvs/opsdroid-13bLHlYD/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/fabiorosado/.local/share/virtualenvs/opsdroid-13bLHlYD/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fabiorosado/.local/share/virtualenvs/opsdroid-13bLHlYD/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/__main__.py", line 196, in main
    opsdroid.load()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/core.py", line 153, in load
    self.start_connectors(self.modules["connectors"])
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/core.py", line 248, in start_connectors
    self.eventloop.run_until_complete(connector.connect(self))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/fabiorosado/Documents/GitHub/opsdroid/opsdroid/connector/slack/__init__.py", line 50, in connect
    connection = await self.slacker.rtm.start()
  File "/Users/fabiorosado/.local/share/virtualenvs/opsdroid-13bLHlYD/lib/python3.6/site-packages/aioslacker/__init__.py", line 97, in __request
    raise Error(response.error)
slacker.Error: invalid_auth
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 511, in __del__
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/unix_events.py", line 65, in close
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/unix_events.py", line 146, in remove_signal_handler
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```
