### ISSUE TITLE
Telegram connector crashes when receiving a message from a channel

### ISSUE THREAD

**Issue by iobreaker** [opsdroid/opsdroid#839]
Hi,

I have found an issue that make telegram connector craches when receiving a message from a channel. the problem is that the json does not contain a **message**  entry

```
DEBUG opsdroid.core: Parsing input: hi
DEBUG opsdroid.core: Processing parsers...
DEBUG opsdroid.connector.telegram: {'update_id': 539026669, 'channel_post': {'message_id': 10, 'chat': {'id': -1001448219498, 'title': 'test-channel', 'type': 'channel'}, 'date': 1550093042, 'text': 'hi'}}
DEBUG opsdroid.connector.telegram: Responding with: Hi IObreaker

DEBUG asyncio: Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/bin/opsdroid", line 11, in <module>
    load_entry_point('opsdroid==0.14.1', 'console_scripts', 'opsdroid')()
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/opsdroid/__main__.py", line 197, in main
    opsdroid.run()
  File "/usr/lib/python3.6/site-packages/opsdroid/core.py", line 135, in run
    self.eventloop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 164, in listen
    await self._get_messages()
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 144, in _get_messages
    await self._parse_message(json)
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 96, in _parse_message
    if result["message"]["text"]:
KeyError: 'message'
```

Testing if "message" in result before parsing should correct this issue in function in function **async def _parse_message(self, response):**

"Telegram changes many entries name, testing if they exists is mandatory before processing to avoid exception"

opsdroid v0.14.1
Python 3.6.7

Opsdroid rocks :-)
Regards

**Comment by jacobtomlinson** [comment]
@iobreaker you seem to be raising some great issues and engaging in discussions in a very productive way. I'd like to send you some [opsdroid stickers](https://medium.com/opsdroid/contributor-sticker-packs-738058ceda59) to say thank you. Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some!

**Comment by iobreaker** [comment]
Thanks @jacobtomlinson it's a pleasure :-)
