### ISSUE TITLE
Telegram connector cannot find username in json response

### ISSUE THREAD

**Issue by iobreaker** [opsdroid/opsdroid#840]
Hi,

Evry time i send a message to opsdroid bot using telegram, the module crashes parsing the json response file

```
DEBUG opsdroid.connector.telegram: {'update_id': 539000683, 'channel_post': {'message_id': 15, 'chat': {'id': -1002528219498, 'title': 'vLab', 'type': 'channel'}, 'date': 1550000742, 'text': 'hi'}}
DEBUG opsdroid.connector.telegram: {'update_id': 539026984, 'message': {'message_id': 53, 'from': {'id': 452280388, 'is_bot': False, 'first_name': 'IOBreaker', 'language_code': 'en'}, 'chat': {'id': 452266388, 'first_name': 'IOBreaker', 'type': 'private'}, 'date': 1550000813, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}
DEBUG asyncio: Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/bin/opsdroid", line 11, in <module>
    load_entry_point('opsdroid==0.14.1', 'console_scripts', 'opsdroid')()
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/opsdroid/__main__.py", line 197, in main
    opsdroid.run()
  File "/usr/lib/python3.6/site-packages/opsdroid/core.py", line 135, in run
    self.eventloop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 163, in listen
    await self._get_messages()
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 143, in _get_messages
    await self._parse_message(json)
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 99, in _parse_message
    user = result["message"]["from"]["username"]
KeyError: 'username'
```

The problem is because the function  async def _parse_message(self, response): the parsing method look for username entry

`user = result["message"]["from"]["username"]`

According to the log, **username** entry does not exist but **first_name** exists

I do not know if it's a new changes in telegram response API but i think the problem is coming from  this.

opsdroid v0.14.1
Python 3.6.7

Opsdroid rocks :-)
Regards

**Comment by FabioRosado** [comment]
Hello @iobreaker thank you for raising this issue. The telegram api might have changed since I added the connector to the core. 

I have some time today so I will fix this issue in the next couple of hours, let me know if you encounter any further issues 😀👍

**Comment by iobreaker** [comment]
Hi,

You are welcome:-)

Yes I think telegram has changed a lot of things, the problem is not only related to the username entry but to "all" entries, sometime **text** exist (in one to one chat) but for channel chat it's missing.

I think a review of the new entries in response file is becoming mandatory for all types of responses :-(

Example :

`
DEBUG opsdroid.connector.telegram: {'update_id': 539026701, 'channel_post': {'message_id': 16, 'chat': {'id': -1001448219498, 'title': 'test-lab', 'type': 'channel'}, 'date': 1550123045, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}
DEBUG opsdroid.connector.telegram: {'update_id': 539026702, 'channel_post': {'message_id': 17, 'chat': {'id': -1001448219498, 'title': 'test-lab', 'type': 'channel'}, 'date': 1550123049, 'text': 'hi'}}
DEBUG opsdroid.connector.telegram: {'update_id': 539026703, 'channel_post': {'message_id': 18, 'chat': {'id': -1001448219498, 'title': 'test-lab', 'type': 'channel'}, 'date': 1550123101, 'text': 'thx'}}
DEBUG opsdroid.connector.telegram: {'update_id': 539026704, 'message': {'message_id': 80, 'from': {'id': 452282388, 'is_bot': False, 'first_name': 'IOBreaker', 'language_code': 'fr'}, 'chat': {'id': -364669643, 'title': 'test-lab', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1550123156, 'group_chat_created': True}}
DEBUG asyncio: Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/bin/opsdroid", line 11, in <module>
    load_entry_point('opsdroid==0.14.1', 'console_scripts', 'opsdroid')()
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/opsdroid/__main__.py", line 197, in main
    opsdroid.run()
  File "/usr/lib/python3.6/site-packages/opsdroid/core.py", line 135, in run
    self.eventloop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 163, in listen
    await self._get_messages()
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 143, in _get_messages
    await self._parse_message(json)
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 97, in _parse_message
    if "message" in result and text in result:
NameError: name 'text' is not defined
ERROR asyncio: Unhandled error in exception handler
`
Telegram should standardize the response
 
Best Regards

**Comment by iobreaker** [comment]
Hi

as a really quick fix i changed the if test line to

`
    async def _parse_message(self, response):
        """Handle logic to parse a received message.

        Since everyone can send a private message to any user/bot
        in Telegram, this method allows to set a list of whitelisted
        users that can interact with the bot. If any other user tries
        to interact with the bot the command is not parsed and instead
        the bot will inform that user that he is not allowed to talk
        with the bot.

        We also set self.latest_update to +1 in order to get the next
        available message (or an empty {} if no message has been received
        yet) with the method self._get_messages().

        Args:
            response (dict): Response returned by aiohttp.ClientSession.

        """
        for result in response["result"]:
            _LOGGER.debug(result)
            if "message" in result and "text" in result["message"]:            <---------------
                user = result["message"]["from"]["first_name"]                   <---------------

                message = Message(
                    user,
                    result["message"]["chat"],
                    self,
                    result["message"]["text"])

                if not self.whitelisted_users or \
                        user in self.whitelisted_users:
                    await self.opsdroid.parse(message)
                else:
                    message.text = "Sorry, you're not allowed " \
                                   "to speak with this bot."
                    await self.respond(message)
                self.latest_update = result["update_id"] + 1

`
and now it's working with channel, group and private chat

Regards

**Comment by FabioRosado** [comment]
I had some time to have a look at it. In my end things are working, but perhaps is because I set up my own username.

How are you trying to talk to the bot? private message or from a channel? I am going to change things a bit because I want the username and first_name to be shown 👍

**Comment by jacobtomlinson** [comment]
Thanks for raising this @iobreaker (and thanks for picking it up @FabioRosado ). 

_For future reference if you use three back-ticks (`` ``` ``) instead of one when putting code blocks on github you get nicer formatting. I've gone through and edited your comments to use this._

**Comment by iobreaker** [comment]
Hi,
@jacobtomlinson Thanks a lot

@FabioRosado I have both, a channel board and a group board.

Bellow some examples :

**Connecting message :**
```
DEBUG opsdroid.connector.telegram: {'ok': True, 'result': {'id': 758952014, 'is_bot': True, 'first_name': 'Test-Bot', 'username': 'TestBot'}}
```

**Channel message (Privacy mode On) - No answer :**
```
Channel message (privacy mode on):
DEBUG opsdroid.connector.telegram: {'update_id': 539026742, 'channel_post': {'message_id': 39, 'chat': {'id': -1001448219498, 'title': 'vLab', 'type': 'channel'}, 'date': 1550212557, 'text': 'hi'}}
```

**Channel message (Privacy mode Off) - no answer :**
```
DEBUG opsdroid.connector.telegram: {'update_id': 539026745, 'channel_post': {'message_id': 40, 'chat': {'id': -1001448219498, 'title': 'vLab', 'type': 'channel'}, 'date': 1550212942, 'text': '@TestBot thanks', 'entities': [{'offset': 0, 'length': 10, 'type': 'mention'}]}}
```

**Adding bot to a group log :**
```
DEBUG opsdroid.connector.telegram: {'update_id': 539026743, 'message': {'message_id': 109, 'from': {'id': 452298658, 'is_bot': False, 'first_name': 'IOBreaker', 'language_code': 'en'}, 'chat': {'id': -372167814, 'title': 'vLab-Group', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1550212656, 'group_chat_created': True}}
```

**Group message (Privacy mode Off) - With Answer  -message -> @TestBot hi  :**
```
DEBUG opsdroid.connector.telegram: {'update_id': 539026744, 'message': {'message_id': 110, 'from': {'id': 452298658, 'is_bot': False, 'first_name': 'IOBreaker', 'language_code': 'fr'}, 'chat': {'id': -372167814, 'title': 'vLab-Group', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1550212812, 'text': '@TestBot hi', 'entities': [{'offset': 0, 'length': 10, 'type': 'mention'}]}}
DEBUG opsdroid.core: Parsing input: @TestBot hi
DEBUG opsdroid.core: Processing parsers...
DEBUG opsdroid.memory: Getting seen from memory.
DEBUG opsdroid.database.sqlite: Getting seen from sqlite
DEBUG opsdroid.connector.telegram: Responding with: Hello IOBreaker
DEBUG aiosqlite: executing functools.partial(<function connect.<locals>.connector at 0x7fae9aa10d90>)
DEBUG aiosqlite: returning <sqlite3.Connection object at 0x7fae9cd0dab0>
DEBUG aiosqlite: executing functools.partial(<built-in method cursor of sqlite3.Connection object at 0x7fae9cd0dab0>)
DEBUG aiosqlite: returning <sqlite3.Cursor object at 0x7fae9b329e30>
DEBUG aiosqlite: executing functools.partial(<built-in method execute of sqlite3.Cursor object at 0x7fae9b329e30>, 'SELECT data FROM Test-Bot_table WHERE key=?', ('seen',))
DEBUG aiosqlite: returning <sqlite3.Cursor object at 0x7fae9b329e30>
DEBUG aiosqlite: executing functools.partial(<built-in method fetchone of sqlite3.Cursor object at 0x7fae9b329e30>)
DEBUG aiosqlite: returning ('{"IOBreaker": {"__class__": "datetime", "year": 2019, "month": 2, "day": 15, "hour": 7, "minute": 5, "second": 22, "microsecond": 940374}}',)
DEBUG aiosqlite: executing functools.partial(<built-in method close of sqlite3.Connection object at 0x7fae9cd0dab0>)
DEBUG aiosqlite: returning None
DEBUG opsdroid.memory: Putting seen to memory
DEBUG opsdroid.database.sqlite: Putting seen into sqlite
DEBUG aiosqlite: executing functools.partial(<function connect.<locals>.connector at 0x7fae9b33ad90>)
DEBUG aiosqlite: returning <sqlite3.Connection object at 0x7fae9c6433b0>
DEBUG aiosqlite: executing functools.partial(<built-in method cursor of sqlite3.Connection object at 0x7fae9c6433b0>)
DEBUG aiosqlite: returning <sqlite3.Cursor object at 0x7fae9b329e30>
DEBUG aiosqlite: executing functools.partial(<built-in method execute of sqlite3.Cursor object at 0x7fae9b329e30>, 'DELETE FROM Test-Bot_table WHERE key=?', ('seen',))
DEBUG aiosqlite: returning <sqlite3.Cursor object at 0x7fae9b329e30>
DEBUG aiosqlite: executing functools.partial(<built-in method execute of sqlite3.Cursor object at 0x7fae9b329e30>, 'INSERT INTO Test-Bot_table VALUES (?, ?)', ('seen', '{"IOBreaker": {"__class__": "datetime", "year": 2019, "month": 2, "day": 15, "hour": 7, "minute": 58, "second": 53, "microsecond": 784355}}'))
DEBUG aiosqlite: returning <sqlite3.Cursor object at 0x7fae9b329e30>
DEBUG aiosqlite: executing functools.partial(<built-in method close of sqlite3.Connection object at 0x7fae9c6433b0>)
DEBUG aiosqlite: returning None
DEBUG opsdroid.connector.telegram: Successfully responded
```

Hope I answred to your question :-)

Kind Regards

**Comment by iobreaker** [comment]
@FabioRosado the try block has to be extended because if the message is comming from a channel like this one

```
DEBUG opsdroid.connector.telegram: {'update_id': 539026745, 'channel_post': {'message_id': 40, 'chat': {'id': -1001448259498, 'title': 'test-lab', 'type': 'channel'}, 'date': 1550212942, 'text': '@TestBot thanks', 'entities': [{'offset': 0, 'length': 10, 'type': 'mention'}]}}
```

the block will rise an exception because first_name does not exist

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/opsdroid/connector/telegram/__init__.py", line 91, in _parse_message
    user = result["message"]["from"]["username"]
KeyError: 'message'

During handling of the above exception, another exception occurred:

```

This test was made with the new code.

I have to look much better if it's a channel behavior (by design) or other strange thing

Regards

**Comment by FabioRosado** [comment]
This is a bit annoying, they should had used the same api response for the different channels, but... their documentation is not the best one so this is no surprise haha

Thank you for testing the PR. I am going to change the things again, if you could test it again I would really really appreciate it 😄 👍

**Comment by FabioRosado** [comment]
I have missed your message before the last one. My PR was updated to handle the case when first_name and username are not provided. Unfortunately, I don't think that we will be able to handle messages sent to a channel message, mostly because the user field is missing. 

`Opsdroid.Message` requires you to pass a `user` param so opsdroid knows who is talking and what sort of skills he needs to trigger. The Telegram api doesn't sent a user when a channel message is sent so it won't be possible to handle these cases :/

**Comment by iobreaker** [comment]
Hi @FabioRosado, I decided to write the code for handling this telegram response **inconsistency** 

I think the best way to do it is to split the process into :

- Private messages (direct message, no @botName)
- Group messages (with and without @botName)
- Channel message (messages will be ignored for the moment)

It will make maintenance more simple as specification handling too

i did not refactor the code, sorry for that, but it's working, i tested it using many situations
I added debug messages and error messages. (please feel free to change the text of the error messages :-)  )

```
DEBUG opsdroid.connector.telegram: Channel type is : private
```

**The code :**
```
    async def _parse_message(self, response):
        for result in response["result"]:
            _LOGGER.debug(result)
            type = None
            if 'channel_post' in result:
                if 'chat' in result['channel_post']:
                    if 'type' in result['channel_post']['chat']:
                        type = result['channel_post']['chat']['type']
                        _LOGGER.debug("Channel type is : " + str(type))
                    else:
                        _LOGGER.error("Cannot determine the chat type, it is so strange ")
                else:
                    _LOGGER.error("Cannot find chat entry in channel response, it is so weird")
            elif 'message' in result:
                if 'chat' in result['message']:
                    if 'type' in result['message']['chat']:
                        type = result['message']['chat']['type']
                        _LOGGER.debug("Channel type is : " + str(type))
                    else:
                        _LOGGER.debug("ERROR : Cannot determine the chat type, it is so strange ")
                else:
                    _LOGGER.error("Cannot find chat entry in response, it is so weird")
            
            user = None
            if type is not None:
                if type.upper() == 'CHANNEL':
                    _LOGGER.debug("Ignoring channel message id " + str(result['channel_post']['message_id']))
                elif type.upper() == 'GROUP':
                    if 'username' in result["message"]["from"]:
                        user = result["message"]["from"]["username"]
                    elif 'first_name' in result["message"]["from"]:
                        user = result["message"]["from"]["first_name"]
                elif type.upper() == 'PRIVATE':
                    if 'username' in result["message"]["from"]:
                        user = result["message"]["from"]["username"]
                    elif 'first_name' in result["message"]["from"]:
                        user = result["message"]["from"]["first_name"]
            
            if type is not None and user is not None:
                message = Message(user, result["message"]["chat"], self, result["message"]["text"])
                if not self.whitelisted_users or user in self.whitelisted_users:
                    await self.opsdroid.parse(message)
                else:
                    message.text = "Sorry, you're not allowed to speak with this bot."
                    await self.respond(message)
                
            self.latest_update = result["update_id"] + 1
```

1. Channel message test

```
DEBUG opsdroid.connector.telegram: {'update_id': 539026751, 'channel_post': {'message_id': 43, 'chat': {'id': -1001448219498, 'title': 'vLab', 'type': 'channel'}, 'date': 1550271810, 'text': 'hi'}}
DEBUG opsdroid.connector.telegram: Channel type is : channel
DEBUG opsdroid.connector.telegram: Ignoring channel message id 43



DEBUG opsdroid.connector.telegram: {'update_id': 539026752, 'channel_post': {'message_id': 44, 'chat': {'id': -1001448219498, 'title': 'vLab', 'type': 'channel'}, 'date': 1550271938, 'text': '@testBot hi', 'entities': [{'offset': 0, 'length': 10, 'type': 'mention'}]}}
DEBUG opsdroid.connector.telegram: Channel type is : channel
DEBUG opsdroid.connector.telegram: Ignoring channel message id 44
```



2. Group message test

```
DEBUG opsdroid.connector.telegram: {'update_id': 539026753, 'message': {'message_id': 115, 'from': {'id': 452282388, 'is_bot': False, 'first_name': 'IOBreaker', 'language_code': 'fr'}, 'chat': {'id': -372167814, 'title': 'vLab-Group', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1550271987, 'text': 'thanks'}}
DEBUG opsdroid.connector.telegram: Channel type is : group
DEBUG opsdroid.core: Parsing input: thanks
DEBUG opsdroid.core: Processing parsers...
DEBUG opsdroid.connector.telegram: Successfully responded



DEBUG opsdroid.connector.telegram: {'update_id': 539026754, 'message': {'message_id': 117, 'from': {'id': 452282388, 'is_bot': False, 'first_name': 'IOBreaker', 'language_code': 'fr'}, 'chat': {'id': -372167814, 'title': 'vLab-Group', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1550272017, 'text': '@testBot merci', 'entities': [{'offset': 0, 'length': 10, 'type': 'mention'}]}}
DEBUG opsdroid.connector.telegram: Channel type is : group
DEBUG opsdroid.core: Parsing input: @testBot merci
DEBUG opsdroid.core: Processing parsers...
DEBUG opsdroid.connector.telegram: Successfully responded
```


3. Private message test

```
DEBUG opsdroid.connector.telegram: {'update_id': 539026756, 'message': {'message_id': 121, 'from': {'id': 452282388, 'is_bot': False, 'first_name': 'IOBreaker', 'language_code': 'fr'}, 'chat': {'id': 452282388, 'first_name': 'IOBreaker', 'type': 'private'}, 'date': 1550272090, 'text': 'hi'}}
DEBUG opsdroid.connector.telegram: Channel type is : private
DEBUG opsdroid.core: Parsing input: hi
DEBUG opsdroid.core: Processing parsers...
DEBUG opsdroid.connector.telegram: Successfully responded
```


hope that will help
Kind Regards

**Comment by FabioRosado** [comment]
Heya, apologies it took me so long to reply.

Mostly the changes that you are suggesting here are somewhat what I have implemented on the last iteration of my telegram PR - the only difference is that I didn't logged any message when the user talks in the channel - so the message `Ignoring channel message id` won't be shown.

Do you think this would be useful? If yes I'm happy to include on the PR - bear in mind that I did update the documentation explaining that the bot won't interact with messages sent from a channel.

Let me know what you think @iobreaker 👍

**Comment by iobreaker** [comment]
Hi @FabioRosado, no problem there is a lot of things to do in one day and sometimes 24h is not enough :-)

##

**About displaying the** `Ignoring channel message`, i think that each interaction must be logged at least in debug mode, this will help in case of debugging or understanding why there is no answer ( because not all users RTFM :-)  ) .

##

if you agree, I will rather start from the "needs" to arrive to a list of specs/rules (more global not only for Telegram connector), **perhaps some ideas for some next futures :-)**

1. A bot can be contacted in private room by :
- Admin user : for admin command like, disabling skill, enabling skill, reloading config, ...
-  Authorized user : to discuss with the bot and ask for skills

2. A bot can be contacted in group room by :
- Admin user : to ask for skills (admin command must be passed only on private room)
-  Authorized user : to discuss with the bot and ask for skills

* Messages to the bot must be prefixed with the bot username  (not all message in a group room are for the bot)

*Answer from the bot must all be prefixed by the username the bot is responding to  (because the bot can have plenty of persons asking for things in the same group room)

> A channel is like a message board, only used to inform not to interact

3. A bot **cannot** be contacted in Channel room by :
- The bot can send message to a channel room about actions in progress (chatops)

> The wonderful thing is to be able to allow skills by users (nice to have)


I am working on some of theses rules with rasa nlu ,for example if prefixing the message with @botname no intent is detected so must filter username and send only the phrase.

##

Thanks for all @FabioRosado and @jacobtomlinson 

Kind Regards

**Comment by FabioRosado** [comment]
I agree with you that perhaps it should be better to log a message saying that messages in a channel will be ignored.

If memory doesn’t fail me, Telegram is the only connector in which opsdroid won’t be able to interact with the channel - all others send the username with the request response.

I added a list of authorised users that can talk with the bot, so technically you have what you mentioned - we could add two lists for admins and other for allowed users but I guess you could do the same logic on a skill that you are passing since you can always get the `connector.config` and access everything that’s in the connector config.

There is an issue with using a list of names to allow users to interact with the bot. I believe it was Cadair that found out that you can pass the constraints by changing your name in matrix.  I am going to assume that you could work around in other connectors as well. The only way to mitigate this would be to use an user id instead of the name but we haven’t implemented this in many places.

I have been thinking that we should try to handle authorised users somehow, but haven’t figured the best way to do it other than using the userid like Cadair did with the matrix connector.

As for prefixing the bot username to talk with the bot. This has been something discussed in the past, but we haven’t decided on the right course of action mostly because you could just change the rules within your skills by adding it to the `regex_matcher`.

It might be a good idea to give it a thought - perhaps we could add something in the `config.yaml` to trigger bot name on and off? 

Comparing to skills the connectors are pretty dumb - they just get all the info from a chat service and send the reply to them. The big bulk of work will be made my the skills. 

It might be interesting to explore more about how we can enhance the connectors and skills in order to improve the workflow for everybody.

Finally, apologies for the weird English and text formation, I’m typing on mobile haha

**Comment by iobreaker** [comment]
Hi @FabioRosado 

Totaly agree :-)

I think when the fix will be merged this issue and the one related to #839 can be closed

Regards

**Comment by FabioRosado** [comment]
I'm off tomorrow so I'll try to finally fix these two issues and implement the suggested bits and bobs from our chats 😄 👍

**Comment by FabioRosado** [comment]
I have just submitted the update for the PR - I tried to sort as many issues as possible but some are still missing. 
With this update you can:
 - get a logging message when a user talks in the channel
- whitelist users by nickname or userID

I haven't worked on the issue where the bot should talk in the channel, feel free to add the functionality with a PR - but perhaps this could be achieved with a skill.

As for using the botname to talk to it, this will be an issue that will have to be addressed outside the Telegram PR as it will impact all the connectors - I will try to work on it later.

Let me know what you think @iobreaker  😄 👍

**Comment by iobreaker** [comment]
hi @FabioRosado 

Perfect, you've done the max about this subject. thanks a lot

About the botname issue, I agree with you, this should be addressed outside of any connector. I think Message subject should evolve to be able to pass the whole message, the text message (without the senders name/nickname) and the rest of information already available.

P.S : About users authorization, i think this should me managed outside of any skills by using a sort of middleware that can check 

- if user X has the right to execute skill Y
- if skill Y can be executed in public or private room

This would be awesome if opsdroid is used like a chatops

Let me know what you think @FabioRosado 😄 👍

**Comment by FabioRosado** [comment]
Now that the Telegram PR was merged into core everything should be working fine for you @iobreaker 
As for your suggestion I would like to have @jacobtomlinson  opinion on them as he will be the right person to give feedback on those suggestions 😄

**Comment by jacobtomlinson** [comment]
These are definitely interesting suggestions. We could implement this with constraints. If we added a `@constrain_admin` constraint then those could be used within skills. We could also have some way (similar to what @iobreaker has suggested) to mark a skill as an admin skill in the config and therefore automatically adds that constraint to all skills within.

Could you please open a new issue to propose that so we can discuss it properly there?

**Comment by iobreaker** [comment]
Thanks @jacobtomlinson 
This modification/futures can bring the ability to opsdroid admins to remotely issue private commands like
- Get skills info
- Install skills
- Remove skills
- Disable skills
- Get X lines of skill's log
- Reload opsdroid config
- Get private/admin stats
- Get X lines of opsdroid logs
- Add authorization
- Remove Authorization
- Activate/deactivate connectors
- ...


This will bring the ops capabilities to opsdroid ;-)
